/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_AccDon (void);
GtkWidget* create_window_GSDon (void);
GtkWidget* create_window_GSDonAjoutModif (void);
GtkWidget* create_window_DonDS (void);
GtkWidget* create_window_DonRS (void);
GtkWidget* create_window_AccGETS (void);
GtkWidget* create_window_GETSAjoutModif (void);
GtkWidget* create_window_GETSRecherche (void);
GtkWidget* create_window_GETSSupprimer (void);
GtkWidget* create_window_GETSModif (void);
GtkWidget* create_window_GETSAfficheRegion (void);
GtkWidget* create_window_GETSAfficheCapacite (void);
GtkWidget* create_window_AccAdmin (void);
GtkWidget* create_window_AdminAffUserRole (void);
GtkWidget* create_window_AdminGUsers (void);
GtkWidget* create_window_AdminGUAM (void);
GtkWidget* create_window_AdminDashboard (void);
GtkWidget* create_window_AccGDPS (void);
GtkWidget* create_window_GDPS (void);
GtkWidget* create_window_GDPSPourcentage (void);
GtkWidget* create_window_GDPSSPD (void);
GtkWidget* create_window_GDPSAjoutModif (void);
GtkWidget* create_window_AccGFD (void);
GtkWidget* create_window_GFD (void);
GtkWidget* create_window_GFDAM (void);
GtkWidget* create_window_GDF_REV_ETS (void);
GtkWidget* create_window_AccGRDVD (void);
GtkWidget* create_window_GRDVDHistorique (void);
GtkWidget* create_window_GRDVD (void);
GtkWidget* create_window_GRDVDAM (void);
GtkWidget* create_window_GRDVDCrenaux1 (void);
GtkWidget* create_window_GRDVDCrenaux2 (void);
GtkWidget* create_window_auth (void);
